before:
  hooks:
    - go mod download
builds:
  - id: gobl.cii
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    main: ./cmd/gobl.cii
    binary: gobl.cii

archives:
  - id: gobl.cii
    builds:
      - gobl.cii
    format: tar.gz
    name_template: "gobl.cii_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    wrap_in_directory: true

checksum:
  name_template: "checksums.txt"
snapshot:
  name_template: "{{ .Tag }}"
changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
release:
  github:
    owner: invopop
    name: gobl.cii
  prerelease: auto